sudo: required
dist: trusty

services:
  - docker

env:
  matrix:
    - COMPILER=gcc
    - COMPILER=llvm

stages:
  - build
  - trigger

jobs:
  include:
    - stage: build
      script: echo $COMPILER
    - stage: trigger

# Don't send e-mail notifications
notifications:
  email: false