name: linux

on: [push, pull_request]

jobs:

  default:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        LCG: ["dev3/x86_64-centos7-gcc11-opt",
              "dev4/x86_64-centos7-gcc11-opt"]
    steps:
    - name: Prepare Artifact Name
      run: |
          artifact_name="${{ matrix.LCG }}"
          artifact_name=$(echo -n "${artifact_name}" | sed -e 's@/@@g')
          echo "ARTIFACT_NAME=${artifact_name}" >> $GITHUB_ENV

    - uses: actions/checkout@v3
    - uses: cvmfs-contrib/github-action-cvmfs@v3
    - uses: aidasoft/run-lcg-view@v3
      with:
        release-platform: ${{ matrix.LCG }}
        run: |
          mkdir build
          cd build
          unset CPATH
          echo "::group::CMakeConfig"
          cmake -GNinja \
            -DDD4HEP_USE_GEANT4=ON \
            -DBoost_NO_BOOST_CMAKE=ON \
            -DDD4HEP_USE_LCIO=ON \
            -DDD4HEP_USE_EDM4HEP=OFF \
            -DDD4HEP_USE_TBB=ON \
            -DDD4HEP_USE_HEPMC3=ON \
            -DDD4HEP_BUILD_DEBUG=OFF \
            -DBUILD_TESTING=ON \
            -DDD4HEP_DEBUG_CMAKE=ON \
            -DDD4HEP_USE_XERCESC=ON \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_CXX_FLAGS="-fdiagnostics-color=always"  \
            -DCMAKE_CXX_STANDARD=17 ..
          echo "::group::Compile"
          ninja install
          . ../bin/thisdd4hep.sh
          echo "::group::Test"
          ctest --output-on-failure -j4 --output-junit TestResults_1.xml
          echo "::group::CMakeExamples"
          cd ../examples/
          mkdir build
          cd build
          cmake -GNinja \
            -DBoost_NO_BOOST_CMAKE=ON \
            -DDD4HEP_USE_XERCESC=ON \
            -DCMAKE_CXX_STANDARD=17 ..
          echo "::group::CompileExamples"
          ninja install
          echo "::group::TestExamples"
          ctest --output-on-failure -j2 --output-junit TestResults_2.xml

    - name: Upload test results
      uses: actions/upload-artifact@v3
      with:
        name: Test Results ${{ env.ARTIFACT_NAME }}
        path: |
           /home/runner/work/DD4hep/DD4hep/build/TestResults_1.xml
           /home/runner/work/DD4hep/DD4hep/examples/build/TestResults_2.xml


  non-shared:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        LCG: ["LCG_102/x86_64-centos7-gcc11-opt"]
    steps:
    - uses: actions/checkout@v3
    - uses: cvmfs-contrib/github-action-cvmfs@v3
    - uses: aidasoft/run-lcg-view@v3
      with:
        release-platform: ${{ matrix.LCG }}
        run: |
          mkdir build
          cd build
          unset CPATH
          echo "::group::CMakeConfig"
          cmake -GNinja \
            -DDD4HEP_USE_GEANT4=ON \
            -DBoost_NO_BOOST_CMAKE=ON \
            -DDD4HEP_USE_LCIO=ON \
            -DDD4HEP_USE_EDM4HEP=OFF \
            -DDD4HEP_USE_TBB=ON \
            -DDD4HEP_USE_HEPMC3=ON \
            -DDD4HEP_BUILD_DEBUG=OFF \
            -DBUILD_TESTING=ON \
            -DDD4HEP_DEBUG_CMAKE=ON \
            -DBUILD_SHARED_LIBS=OFF \
            -DDD4HEP_USE_XERCESC=ON \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_CXX_FLAGS="-fdiagnostics-color=always"  \
            -DCMAKE_CXX_STANDARD=17 ..
          echo "::group::Compile"
          ninja

  event_file:
    if: github.repository_owner == 'andresailer' || github.event_name == 'pull_request'
    name: "Upload Event Payload"
    runs-on: ubuntu-latest
    steps:
    - name: Upload
      uses: actions/upload-artifact@v3
      with:
        name: Event File
        path: ${{ github.event_path }}
